### ISSUE TITLE
No support for multipart/form-data

### ISSUE THREAD

**Issue by dylrei** [graphql-python/graphql-django-view#5]
Currently, query is not parsed if the `content_type` is `multipart/form-data`. 

Submitting a PR to handle this case. Uploaded files should then be accessible in `mutate_and_get_payload` in `info.request_context.POST[filename]`

**Comment by rattrayalex** [comment]
This appears to have been merged: https://github.com/graphql-python/graphql-django-view/pull/6

perhaps this issue should be closed?

**Comment by dylrei** [comment]
Yep, sorry about that. Closing.
